/**
 * @stream-overlay/shared — Message Protocol
 *
 * The canonical TypeScript contract for all messages that flow through the broker.
 * Every service in the ecosystem (Streamer.bot, overlay, future web app) must
 * conform to these types.
 *
 * - No runtime logic lives here — types and interfaces only.
 * - Payload shapes are derived from session-lifecycle.md and json-schema.md.
 *   Do not invent fields that don't exist in those docs.
 * - Topic strings live in topics.ts — import from there, never hardcode.
 */

// ============================================================
// CORE ENVELOPE
// ============================================================

/**
 * Every message through the broker must conform to this shape.
 * The broker routes on `topic`; it does not inspect `payload`.
 */
export interface BrokerMessage<P = unknown> {
  /** UUID v4 — unique per message, generated by the sender before publishing */
  id: string;
  /** Dot-notation topic string, e.g. "overlay.spawn" or "lotat.session.start" */
  topic: string;
  /** Stable human-readable sender name, e.g. "streamerbot", "overlay" */
  sender: string;
  /** Unix epoch milliseconds — Date.now() at time of send */
  timestamp: number;
  /** Topic-specific payload — shape defined by the interfaces below */
  payload: P;
}

// ============================================================
// CLIENT REGISTRATION HANDSHAKE
//
// Flow: client connects → sends ClientHello → broker responds ClientWelcome
// All clients (Streamer.bot, overlay, future apps) use the same handshake.
// ============================================================

/**
 * Sent by a client immediately after the WebSocket connection opens.
 * Must be the first message sent on a new connection.
 */
export interface ClientHello {
  type: "client.hello";
  /**
   * Human-readable, stable client name.
   * Used in system.client.connected/disconnected events and broker logs.
   * Must be consistent across reconnects (not randomly generated each time).
   * Known values: "streamerbot" | "overlay"
   */
  name: string;
  /**
   * Topic patterns this client wants to receive.
   * Supports single-level wildcards: "lotat.*" matches "lotat.session.start"
   * but NOT "lotat.visual.spawn" (that would require a separate "lotat.visual.*").
   * Use wildcard constants from topics.ts to avoid typos.
   */
  subscriptions: string[];
}

/**
 * Sent by the broker in response to a valid ClientHello.
 * Confirms the client is registered and subscriptions are active.
 */
export interface ClientWelcome {
  type: "client.welcome";
  /** Broker-assigned unique ID for this connection session */
  clientId: string;
  /** Human-readable names of all currently connected clients (excluding this one) */
  connectedClients: string[];
}

// ============================================================
// SHARED PRIMITIVES
// ============================================================

/** 2D position on the 1920×1080 overlay canvas (pixels) */
export interface CanvasPosition {
  x: number;
  y: number;
}

/**
 * Named animation preset — interpreted by the Phaser overlay renderer.
 * New presets must be supported in the overlay before being sent by Streamer.bot.
 */
export type AnimationPreset =
  | "fade-in"
  | "fade-out"
  | "slide-in-left"
  | "slide-in-right"
  | "slide-in-top"
  | "slide-in-bottom"
  | "bounce"
  | "shake"
  | "pulse"
  | "spin"
  | "none";

// ============================================================
// SYSTEM TOPICS
// ============================================================

/**
 * system.client.connected
 * Published by the broker when a new client completes its ClientHello handshake.
 * Sent to all currently subscribed clients.
 */
export interface SystemClientConnectedPayload {
  clientId: string;
  clientName: string;
}

/**
 * system.client.disconnected
 * Published by the broker when a client's WebSocket connection closes.
 * Sent to all currently subscribed clients.
 */
export interface SystemClientDisconnectedPayload {
  clientId: string;
  clientName: string;
}

/**
 * system.ping
 * Keepalive sent by any client to verify the broker connection is alive.
 * Broker (or any subscriber) should respond with system.pong.
 */
export interface SystemPingPayload {
  /** Optional value echoed back in the pong for round-trip correlation */
  echo?: string;
}

/**
 * system.pong
 * Response to a system.ping.
 */
export interface SystemPongPayload {
  echo?: string;
}

// ============================================================
// OVERLAY TOPICS — generic asset management
//
// The overlay is a dumb renderer. Streamer.bot decides what to show
// and when; the overlay renders what it's told.
// ============================================================

/**
 * overlay.spawn
 * Spawn a PNG/JPG/GIF asset at a canvas position.
 *
 * Asset ID strategy:
 * - Ephemeral/one-off assets (alerts, reactions): UUID v4 generated by sender
 * - Persistent/named assets (HUD widgets, meters): human-readable slug
 *   e.g. "chaos-meter", "lotat-hud", "duck-counter"
 *   Named assets can be moved/animated/removed by referencing the same slug.
 */
export interface OverlaySpawnPayload {
  /**
   * Unique asset identifier.
   * Ephemeral: UUID v4. Persistent: human-readable slug (kebab-case).
   * Spawning an asset with an existing ID replaces that asset.
   */
  assetId: string;
  /**
   * Path or URL to the image/GIF asset.
   * Relative paths resolve from packages/overlay/public/ in both dev and prod.
   */
  src: string;
  position: CanvasPosition;
  /** Display width in pixels. If omitted, height must be provided; aspect ratio preserved. */
  width?: number;
  /** Display height in pixels. If omitted, width must be provided; aspect ratio preserved. */
  height?: number;
  /** Phaser depth (z-index). Higher values render on top. Defaults to 0. */
  depth?: number;
  /** Animation to play as the asset appears. Defaults to "none". */
  enterAnimation?: AnimationPreset;
  /** Duration of entry animation in milliseconds. Defaults to 300. */
  enterDuration?: number;
  /**
   * Auto-remove the asset after this many milliseconds.
   * Omit for persistent assets that stay until explicitly removed.
   */
  lifetime?: number;
  /** Exit animation to play when the asset is auto-removed via lifetime. */
  exitAnimation?: AnimationPreset;
  /** Duration of exit animation in milliseconds. Defaults to 300. */
  exitDuration?: number;
}

/**
 * overlay.move
 * Tween an existing asset to a new canvas position.
 */
export interface OverlayMovePayload {
  assetId: string;
  position: CanvasPosition;
  /** Tween duration in milliseconds. 0 = instant snap. Defaults to 300. */
  duration?: number;
}

/**
 * overlay.animate
 * Apply or change an animation on an existing asset without moving it.
 */
export interface OverlayAnimatePayload {
  assetId: string;
  animation: AnimationPreset;
  /** Animation duration in milliseconds. Defaults to 300. */
  duration?: number;
}

/**
 * overlay.remove
 * Remove a specific asset from the canvas.
 */
export interface OverlayRemovePayload {
  assetId: string;
  /** Exit animation to play before the asset is destroyed. Defaults to "none". */
  exitAnimation?: AnimationPreset;
  /** Duration of exit animation in milliseconds. Defaults to 300. */
  exitDuration?: number;
}

/**
 * overlay.clear
 * Remove all assets from the canvas, with optional prefix filter.
 * Use sparingly — prefer overlay.remove for targeted cleanup.
 */
export interface OverlayClearPayload {
  /**
   * If provided, only assets whose IDs start with this prefix are removed.
   * Example: "lotat-" removes all assets with IDs beginning with "lotat-".
   * If omitted, ALL assets are cleared.
   */
  assetIdPrefix?: string;
  /** Exit animation applied to all removed assets. Defaults to "none". */
  exitAnimation?: AnimationPreset;
  /** Duration of exit animation in milliseconds. Defaults to 300. */
  exitDuration?: number;
}

/**
 * overlay.audio.play
 * Play an MP3 sound through the Phaser audio system.
 * OBS browser source must have audio enabled for sounds to reach stream output.
 */
export interface OverlayAudioPlayPayload {
  /**
   * Unique sound instance ID — used to stop this specific sound later.
   * Use a UUID v4 for one-shot sounds; a stable slug for looping ambient audio.
   */
  soundId: string;
  /**
   * Path or URL to the MP3 file.
   * Relative paths resolve from packages/overlay/public/.
   */
  src: string;
  /** Volume from 0 (silent) to 1 (full). Defaults to 1. */
  volume?: number;
  /** Whether to loop the sound indefinitely. Defaults to false. */
  loop?: boolean;
}

/**
 * overlay.audio.stop
 * Stop a playing sound by its instance ID.
 */
export interface OverlayAudioStopPayload {
  /**
   * Sound instance ID to stop.
   * If omitted, ALL currently playing sounds are stopped.
   */
  soundId?: string;
}

// ============================================================
// LOTAT TOPICS — session lifecycle events
//
// Topic sequence mirrors the session-lifecycle.md stage machine:
//   idle → join_open → node_intro → [commander_open?] → [dice_open?]
//       → decision_open → decision_resolving → node_intro → ... → ended → idle
//
// Streamer.bot publishes these. The overlay subscribes to render LotAT UI.
// ============================================================

/**
 * lotat.session.start
 * Stage transition: idle → join_open
 * Signals that a new LotAT session has been initialized and the join phase
 * is about to open. Overlay should prepare any LotAT persistent UI.
 */
export interface LotatSessionStartPayload {
  /** Session-scoped unique ID (UUID v4) — included in all subsequent LotAT events */
  sessionId: string;
  /** Matches story_id from the loaded story JSON */
  storyId: string;
  /** Story display title */
  title: string;
}

/**
 * lotat.session.end
 * Stage transition: ended → idle
 * Session is fully torn down. Overlay should remove all LotAT UI.
 */
export interface LotatSessionEndPayload {
  sessionId: string;
  /** How the session ended */
  reason: "ending-reached" | "zero-join" | "zero-votes" | "fault-abort";
  /**
   * Authored end_state from the ending node.
   * Only present when reason is "ending-reached".
   */
  endState?: "success" | "partial" | "failure";
}

/**
 * lotat.join.open
 * Stage: join_open is now active.
 * Join window is open; chat may type !join.
 */
export interface LotatJoinOpenPayload {
  sessionId: string;
  /** Join window duration in seconds. Fixed at 120 in v1. */
  windowSeconds: number;
}

/**
 * lotat.join.update
 * Stage: join_open — roster changed.
 * A viewer successfully joined; participant count increased.
 */
export interface LotatJoinUpdatePayload {
  sessionId: string;
  /** Lowercased username/login of the viewer who just joined */
  username: string;
  /** Running participant count after this join */
  participantCount: number;
}

/**
 * lotat.join.close
 * Stage: join_open → node_intro (or ended if zero joins).
 * Join phase closed; roster is now frozen.
 */
export interface LotatJoinClosePayload {
  sessionId: string;
  /** Final frozen participant count. 0 = zero-join path (session will end). */
  participantCount: number;
}

/**
 * lotat.node.enter
 * Stage: node_intro
 * Engine has entered a story node. Overlay should render read_aloud, crew_focus,
 * and prepare any mechanic UI (dice or commander) that precedes voting.
 *
 * Payload fields are derived strictly from the authored story JSON schema.
 * Do not add fields that don't exist in json-schema.md.
 */
export interface LotatNodeEnterPayload {
  sessionId: string;
  /** Matches node_id from story JSON */
  nodeId: string;
  nodeType: "stage" | "ending";
  /** Ship section for this node */
  shipSection: string;
  /** Short internal node title */
  title: string;
  /** Stream-facing narration block — read aloud by operator */
  readAloud: string;
  /** Production audio hint, or null if none */
  sfxHint: string | null;
  /** Crew member spotlighted at this node */
  crewFocus: {
    commander: string | null;
    squadMember: string | null;
  };
  /** Chaos increase applied when entering this node */
  chaosDelta: number;
  /**
   * Present only when dice_hook.enabled = true on this node.
   * Overlay uses this to render the dice roll UI before voting opens.
   */
  diceHook?: {
    purpose: string;
    rollWindowSeconds: number;
    successThreshold: number;
  };
  /**
   * Present only when commander_moment.enabled = true on this node.
   * Overlay uses this to render the commander prompt before voting opens.
   */
  commanderMoment?: {
    commander: string;
    prompt: string;
    windowSeconds: number;
  };
  /**
   * Choices available at this node — for overlay display only.
   * Empty array for ending nodes.
   */
  choices: Array<{
    choiceId: string;
    label: string;
    command: string;
  }>;
  /** null for stage nodes; "success" | "partial" | "failure" for ending nodes */
  endState: "success" | "partial" | "failure" | null;
}

/**
 * lotat.vote.open
 * Stage: decision_open
 * Decision window is now live; joined participants may vote.
 */
export interface LotatVoteOpenPayload {
  sessionId: string;
  nodeId: string;
  /** Active choices for this decision window */
  choices: Array<{
    choiceId: string;
    label: string;
    command: string;
  }>;
  /** Decision window duration in seconds. Fixed at 120 in v1. */
  windowSeconds: number;
  /** Number of joined participants in the frozen roster */
  participantCount: number;
}

/**
 * lotat.vote.cast
 * Stage: decision_open — a valid vote was received.
 * Sent each time an eligible participant casts a vote.
 * Overlay can use this to update a live vote tally display.
 */
export interface LotatVoteCastPayload {
  sessionId: string;
  nodeId: string;
  /** Lowercased username of the voter */
  username: string;
  /** The command they voted with (e.g. "!scan") */
  command: string;
  /** Running vote totals after this cast — key is command string, value is vote count */
  voteTotals: Record<string, number>;
  /** How many of the frozen roster have now voted */
  votedCount: number;
  /** Total frozen roster size (denominator for early-close check) */
  participantCount: number;
}

/**
 * lotat.vote.close
 * Stage: decision_resolving (or ended if zero votes)
 * Voting is closed and the winner has been resolved.
 */
export interface LotatVoteClosePayload {
  sessionId: string;
  nodeId: string;
  /** Winning command string, or null if zero valid votes (session ends unresolved) */
  winningCommand: string | null;
  winningChoiceId: string | null;
  /** Authored result_flavor text for the winning choice, or null if unresolved */
  resultFlavor: string | null;
  /** Final vote totals */
  voteTotals: Record<string, number>;
  /** Next node to enter. Null when session is ending (ending node or unresolved). */
  nextNodeId: string | null;
}

/**
 * lotat.dice.open
 * Stage: dice_open
 * Dice roll window is now live; any viewer may type !roll.
 */
export interface LotatDiceOpenPayload {
  sessionId: string;
  nodeId: string;
  /** Authored purpose string — what the roll is for */
  purpose: string;
  /** A roll >= this value is a success */
  successThreshold: number;
  /** Window duration in seconds (authored per-node via dice_hook.roll_window_seconds) */
  windowSeconds: number;
}

/**
 * lotat.dice.roll
 * Stage: dice_open — a viewer used !roll.
 * Sent for every roll attempt while the window is open.
 * Overlay can display each roll result to chat.
 */
export interface LotatDiceRollPayload {
  sessionId: string;
  nodeId: string;
  /** Lowercased username who rolled */
  username: string;
  /** Random value 1–100 */
  rollValue: number;
  successThreshold: number;
  /** True when rollValue >= successThreshold (this roll closes the window on success) */
  isSuccess: boolean;
}

/**
 * lotat.dice.close
 * Stage: dice_open resolved — dice window is over.
 * Overlay should display the authored outcome text, then prepare for voting.
 */
export interface LotatDiceClosePayload {
  sessionId: string;
  nodeId: string;
  outcome: "success" | "failure";
  /** Winning roll value — only present when outcome is "success" */
  winningRoll?: number;
  /** Username of the successful roller — only present when outcome is "success" */
  winningUsername?: string;
  /**
   * Authored outcome text to surface (success_text or failure_text from story JSON).
   * Narrative-only in v1 — does not affect branching or chaos.
   */
  outcomeText: string;
}

/**
 * lotat.commander.open
 * Stage: commander_open
 * Commander moment window is now live. Only the assigned commander user's
 * input commands are accepted during this window.
 */
export interface LotatCommanderOpenPayload {
  sessionId: string;
  nodeId: string;
  /** Which commander owns this moment (matches commander_moment.commander in story JSON) */
  commander: string;
  /** Authored call-to-action text for the commander window */
  prompt: string;
  /** Window duration in seconds (authored per-node via commander_moment.window_seconds) */
  windowSeconds: number;
}

/**
 * lotat.commander.close
 * Stage: commander_open resolved — commander moment is over.
 * Narrative-only in v1 — outcome does not affect branching, chaos, or vote eligibility.
 */
export interface LotatCommanderClosePayload {
  sessionId: string;
  nodeId: string;
  /** success = assigned commander responded; skipped = timeout or no assigned commander */
  outcome: "success" | "skipped";
  /**
   * Authored success_text from story JSON.
   * Only present when outcome is "success".
   */
  successText?: string;
}

/**
 * lotat.chaos.update
 * Emitted each time the chaos total changes (on every node entry where chaosDelta > 0).
 * Overlay uses this to update any chaos meter display.
 */
export interface LotatChaosUpdatePayload {
  sessionId: string;
  /** New cumulative chaos total for this session */
  chaosTotal: number;
  /** Delta applied at the current node (from chaos.delta in story JSON) */
  delta: number;
}

// ============================================================
// SQUAD TOPICS — mini-game events
//
// Pattern: squad.<game>.start | squad.<game>.update | squad.<game>.end
// Known games: duck, clone, pedro, toothless
// ============================================================

/** Shared base for all squad game start events */
export interface SquadGameStartPayload {
  /** Game identifier — matches the topic segment (e.g. "duck", "clone") */
  game: string;
  /** Lowercased username who triggered the game */
  triggeredBy: string;
}

/** Shared base for all squad game update events */
export interface SquadGameUpdatePayload {
  game: string;
  /**
   * Game-specific state snapshot.
   * Shape varies per game — typed per-game interfaces extend this as needed.
   */
  state: Record<string, unknown>;
}

/** Shared base for all squad game end events */
export interface SquadGameEndPayload {
  game: string;
  /**
   * Game-specific result summary.
   * Shape varies per game — typed per-game interfaces extend this as needed.
   */
  result: Record<string, unknown>;
}

// Per-game start payloads

export interface SquadDuckStartPayload extends SquadGameStartPayload {
  game: "duck";
}

export interface SquadCloneStartPayload extends SquadGameStartPayload {
  game: "clone";
}

export interface SquadPedroStartPayload extends SquadGameStartPayload {
  game: "pedro";
}

export interface SquadToothlessStartPayload extends SquadGameStartPayload {
  game: "toothless";
}

// ============================================================
// SQUAD — per-game typed state/result shapes (Prompt 07)
//
// These are the concrete shapes published inside the generic
// SquadGameUpdatePayload.state and SquadGameEndPayload.result fields.
// Renderers cast to these types after reading the game discriminant.
// ============================================================

/** squad.duck.update — state field shape */
export interface SquadDuckUpdateState {
  quackCount: number;
  uniqueQuackerCount: number;
}

/** squad.duck.end — result field shape */
export interface SquadDuckEndResult {
  success: boolean;
  finalQuackCount: number;
  uniqueQuackerCount: number;
}

/** squad.pedro.update — state field shape */
export interface SquadPedroUpdateState {
  mentionCount: number;
}

/** squad.pedro.end — result field shape */
export interface SquadPedroEndResult {
  success: boolean;
  finalMentionCount: number;
}

/** squad.clone.update — state field shape (published on each volley) */
export interface SquadCloneUpdateState {
  round: number;
  /** Comma-separated open positions, e.g. "1,2,4,5" */
  positionsOpen: string;
  eliminatedPosition: number;
}

/** squad.clone.end — result field shape */
export interface SquadCloneEndResult {
  outcome: "win" | "loss";
  eliminatedPosition: number;
  /** Comma-separated winner usernames, or "" if no survivors */
  winners: string;
}

/** Rarity tiers for Toothless rolls */
export type ToothlessRarity = "regular" | "smol" | "long" | "flight" | "party";

/** squad.toothless.end — result field shape */
export interface SquadToothlessEndResult {
  rarity: ToothlessRarity;
  username: string;
  isFirstUnlock: boolean;
}

// ============================================================
// STREAM TOPICS — raw stream platform events
//
// Published by Streamer.bot when Twitch events arrive.
// The overlay uses these to trigger alert visuals and sounds.
// ============================================================

/** stream.sub — a viewer subscribed or resubscribed */
export interface StreamSubPayload {
  /** Lowercased Twitch login */
  username: string;
  displayName: string;
  /** Twitch subscription tier */
  tier: "1000" | "2000" | "3000" | "Prime";
  isGift: boolean;
  /** Cumulative months subscribed — present for resubs */
  months?: number;
}

/** stream.raid — incoming raid from another channel */
export interface StreamRaidPayload {
  username: string;
  displayName: string;
  viewerCount: number;
}

/** stream.follow — a new viewer followed the channel */
export interface StreamFollowPayload {
  username: string;
  displayName: string;
}

/** stream.bits — a viewer cheered bits */
export interface StreamBitsPayload {
  username: string;
  displayName: string;
  /** Bits cheered in this transaction */
  amount: number;
  /** Viewer's total bits given to the channel (all time) */
  totalBitsGiven: number;
  /** Chat message accompanying the cheer, if any */
  message?: string;
}

// ============================================================
// TOPIC → PAYLOAD MAP
//
// Associates every known topic string with its payload interface.
// Used by TypedBrokerMessage<T> to produce fully typed messages.
// If you add a new topic, add it here AND to topics.ts.
// ============================================================

export interface TopicPayloadMap {
  // System
  "system.client.connected": SystemClientConnectedPayload;
  "system.client.disconnected": SystemClientDisconnectedPayload;
  "system.ping": SystemPingPayload;
  "system.pong": SystemPongPayload;

  // Overlay — generic assets
  "overlay.spawn": OverlaySpawnPayload;
  "overlay.move": OverlayMovePayload;
  "overlay.animate": OverlayAnimatePayload;
  "overlay.remove": OverlayRemovePayload;
  "overlay.clear": OverlayClearPayload;

  // Overlay — audio
  "overlay.audio.play": OverlayAudioPlayPayload;
  "overlay.audio.stop": OverlayAudioStopPayload;

  // LotAT — session lifecycle
  "lotat.session.start": LotatSessionStartPayload;
  "lotat.session.end": LotatSessionEndPayload;
  "lotat.join.open": LotatJoinOpenPayload;
  "lotat.join.update": LotatJoinUpdatePayload;
  "lotat.join.close": LotatJoinClosePayload;
  "lotat.node.enter": LotatNodeEnterPayload;
  "lotat.vote.open": LotatVoteOpenPayload;
  "lotat.vote.cast": LotatVoteCastPayload;
  "lotat.vote.close": LotatVoteClosePayload;
  "lotat.dice.open": LotatDiceOpenPayload;
  "lotat.dice.roll": LotatDiceRollPayload;
  "lotat.dice.close": LotatDiceClosePayload;
  "lotat.commander.open": LotatCommanderOpenPayload;
  "lotat.commander.close": LotatCommanderClosePayload;
  "lotat.chaos.update": LotatChaosUpdatePayload;

  // Squad — Duck
  "squad.duck.start": SquadDuckStartPayload;
  "squad.duck.update": SquadGameUpdatePayload;
  "squad.duck.end": SquadGameEndPayload;

  // Squad — Clone
  "squad.clone.start": SquadCloneStartPayload;
  "squad.clone.update": SquadGameUpdatePayload;
  "squad.clone.end": SquadGameEndPayload;

  // Squad — Pedro
  "squad.pedro.start": SquadPedroStartPayload;
  "squad.pedro.update": SquadGameUpdatePayload;
  "squad.pedro.end": SquadGameEndPayload;

  // Squad — Toothless
  "squad.toothless.start": SquadToothlessStartPayload;
  "squad.toothless.update": SquadGameUpdatePayload;
  "squad.toothless.end": SquadGameEndPayload;

  // Stream events
  "stream.sub": StreamSubPayload;
  "stream.raid": StreamRaidPayload;
  "stream.follow": StreamFollowPayload;
  "stream.bits": StreamBitsPayload;
}

/**
 * Helper: produce a fully typed BrokerMessage for a known topic.
 *
 * @example
 * const msg: TypedBrokerMessage<"overlay.spawn"> = {
 *   id: crypto.randomUUID(),
 *   topic: TOPICS.OVERLAY_SPAWN,
 *   sender: CLIENT_NAMES.STREAMERBOT,
 *   timestamp: Date.now(),
 *   payload: { assetId: "pedro-alert", src: "pedro.gif", position: { x: 100, y: 100 } },
 * };
 */
export type TypedBrokerMessage<T extends keyof TopicPayloadMap> =
  BrokerMessage<TopicPayloadMap[T]>;
