#!/usr/bin/env python3
"""
install-hooks.py — Install the SharkStreamerBot pre-commit validation hook.

Run once after cloning or when the hook needs to be reinstalled:
  python3 Tools/StreamerBot/Validation/install-hooks.py

What it does:
  Writes a pre-commit hook to .git/hooks/pre-commit that runs validate.py
  before every commit. If validation fails, the commit is blocked with a
  clear error message pointing to the specific drift or schema issue.

Idempotent — safe to run multiple times.
"""

import os
import stat
import sys

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

PYTHON_EXE = sys.executable or "python3"
HOOK_CONTENT = f"""\
#!/bin/sh
# SharkStreamerBot pre-commit validator
# Installed by Tools/StreamerBot/Validation/install-hooks.py
# Do not edit this file directly — re-run install-hooks.py to regenerate.

\"{PYTHON_EXE}\" "$(git rev-parse --show-toplevel)/Tools/StreamerBot/Validation/validate.py"
exit $?
"""



def find_repo_root(start: str) -> str:
    current = os.path.abspath(start)
    for _ in range(10):
        if os.path.isfile(os.path.join(current, "AGENTS.md")):
            return current
        parent = os.path.dirname(current)
        if parent == current:
            break
        current = parent
    raise RuntimeError(
        "Could not find repo root (AGENTS.md not found). "
        "Run from inside the SharkStreamerBot repo."
    )



def main() -> int:
    script_dir = os.path.dirname(os.path.abspath(__file__))
    try:
        repo_root = find_repo_root(script_dir)
    except RuntimeError as e:
        print(f"ERROR: {e}")
        return 1

    hooks_dir = os.path.join(repo_root, ".git", "hooks")
    if not os.path.isdir(hooks_dir):
        print(f"ERROR: .git/hooks not found at {hooks_dir}")
        print("Make sure you are inside a Git repository.")
        return 1

    hook_path = os.path.join(hooks_dir, "pre-commit")

    # Check for existing hook that isn't ours
    if os.path.isfile(hook_path):
        with open(hook_path, encoding="utf-8") as f:
            existing = f.read()
        if "SharkStreamerBot pre-commit validator" not in existing:
            print(f"WARNING: A pre-commit hook already exists at {hook_path}")
            print("It does not appear to be the SharkStreamerBot validator.")
            answer = input("Overwrite it? [y/N] ").strip().lower()
            if answer != "y":
                print("Aborted. Hook not installed.")
                return 1

    with open(hook_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(HOOK_CONTENT)

    # Make executable (required on Unix/Git Bash; harmless on Windows)
    current_mode = os.stat(hook_path).st_mode
    os.chmod(hook_path, current_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    print(f"✓ Pre-commit hook installed at: {hook_path}")
    print()
    print("The validator will now run automatically before every commit.")
    print(f"Hook interpreter: {PYTHON_EXE}")
    print("To run it manually at any time:")
    print("  python3 Tools/StreamerBot/Validation/validate.py")
    print()
    print("To uninstall, delete the hook file:")
    print(f"  {hook_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
